@startuml

package "Product: Alpha" as PA {
  frame "Endpoints: Alpha" {
    [https://alpha.com]
  }
}
package "Product: Delta" as PD {
  frame "Endpoints: Delta" {
    [https://delta.com]
  }
}

PA <-[hidden]right-> PD

@enduml