@startuml

package "Product: Alpha" as PA {
  frame "Endpoints: Alpha" {
    [https://alpha.com\nhttps://omega.com]
  }
  frame "Finding 2: Alpha" as F2A {
    [https://alpha.com ]
  }
  frame "Finding 1: Alpha" as F1A {
    [https://alpha.com]
  }
}
package "Product: Delta" as PD {
  frame "Endpoints: Delta" {
    [https://delta.com]
  }
}


package "Unassigned Findings" as UF {
  frame "Finding 2" as F2 {
    [https://charlie.com/some/path\nhttps://epsilon.com/some/path]
  }
  frame "Finding 1" as F1 {
    [https://beta.com/some/path]
  }
}


PA -[hidden]right-> PD 
PA -[hidden]down-> UF 
PD -[hidden]down-> UF 

@enduml